import Link from "next/link"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

// layout.tsx
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="bg-gray-900 text-gray-100 min-h-screen">
          <h1 className="text-3xl font-bold mb-4">Welcome to My Layout from the Main Page</h1>
          <Link href="/login">Go to Login</Link>
          {children}
        </div>
      </body>
    </html>
  )
}
